POST http://localhost:8000/clientes/new HTTP/1.1

{
    "Datos de formulario": {
        "csrfmiddlewaretoken":"XCjQGNeTInBy3TVgQZ9ArpJsUJSoQVi3nnnakvmJkoHARMH5X1Uptii0tmoTmiR7",
        "cod_postal":"9999",
        "localidad":"Prueba",
        "provincia":"1"
    }
}

$.ajax({
				type: 'POST',
        url: '/pruebaLocalidad/',
        data: {
          "cod_postal": "9990",
          "localidad":"Prueba",
          "provincia":"1"
        },
        dataType: 'json',
      });