# Generated by Django 2.2.10 on 2020-08-13 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("gestion", "0001_initial"),
        ("gestion", "0002_auto_20190704_1709"),
        ("gestion", "0003_auto_20190705_1600"),
        ("gestion", "0004_auto_20190705_1913"),
        ("gestion", "0005_auto_20190705_1940"),
        ("gestion", "0006_auto_20190718_1239"),
        ("gestion", "0007_pedido_cliente"),
        ("gestion", "0008_auto_20190722_1510"),
        ("gestion", "0009_delete_proveedor"),
        ("gestion", "0010_auto_20191101_1616"),
    ]

    initial = True

    dependencies = [
        ("clientes", "0001_squashed_0004_auto_20191101_1227"),
        ("productos", "0002_auto_20190723_1407"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_provincia", models.CharField(default="AR-", max_length=10)),
                ("provincia", models.CharField(default="Provincia", max_length=50)),
            ],
            options={"ordering": ["provincia"]},
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localidad", models.CharField(max_length=128)),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provincias",
                        to="gestion.Provincia",
                    ),
                ),
                ("cod_postal", models.CharField(max_length=10)),
            ],
            options={"verbose_name_plural": "Localidades", "ordering": ["localidad"]},
        ),
    ]
