# Generated by Django 2.2.3 on 2019-07-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=64)),
                ('calle', models.CharField(max_length=64)),
                ('numero', models.CharField(max_length=6)),
                ('detalles', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=128, unique=True)),
                ('detalles', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('medida', models.CharField(max_length=64)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en $', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='InsumosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='StockInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad en Stock')),
                ('detalles', models.TextField(blank=True)),
                ('insumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=64)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=128)),
                ('telefono', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('calle', models.CharField(max_length=64)),
                ('numero', models.CharField(max_length=4)),
                ('detalles', models.TextField(blank=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='gestion.Localidad')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en $', max_digits=6)),
                ('insumos', models.ManyToManyField(through='gestion.InsumosProducto', to='gestion.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('precio_final', models.DecimalField(decimal_places=2, help_text='Precio en $', max_digits=6)),
                ('detalles', models.TextField(blank=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.Cliente')),
                ('estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gestion.EstadoPedido')),
                ('productos_pedido', models.ManyToManyField(to='gestion.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='gestion.Provincia'),
        ),
        migrations.AddField(
            model_name='insumosproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Producto'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedores',
            field=models.ManyToManyField(to='gestion.Proveedor'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='gestion.Unidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='gestion.Localidad'),
        ),
    ]
