# Generated by Django 2.2.3 on 2019-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidad',
            old_name='nombre',
            new_name='localidad',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='provincia',
            name='cod_provincia',
            field=models.CharField(default='AR-', max_length=10),
        ),
        migrations.AddField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(default='Provincia', max_length=50),
        ),
    ]
