# Generated by Django 2.2.3 on 2019-07-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20190705_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['localidad'], 'verbose_name_plural': 'Localidades'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_fantasia',
        ),
    ]
