# Generated by Django 2.2.3 on 2019-07-18 15:39

from django.db import migrations, models
import proveedores.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20190705_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(help_text='Ingrese el CUIT con el siguiente formato: 20-12345678-9', max_length=13, unique=True, validators=[proveedores.helpers.validar_cuit]),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
