# Generated by Django 2.2.3 on 2019-07-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='insumosproducto',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='insumosproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos_pedido',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='insumos',
        ),
        migrations.RemoveField(
            model_name='stockinsumo',
            name='insumo',
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='InsumosProducto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='StockInsumo',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
