version: "3.7" # Update to 3.8

services:
    web:
        # build: .
        image: enredarte_web:latest
        command: python manage.py runserver 0.0.0.0:8000 --settings=enredarte.settings
        volumes:
            - .:/usr/app/enredarte
        ports:
            # Map port 8000 from CONTAINER to access at `localhost:8000`
            - "8000:8000"
            - "4000:4000" # ptvsd port for debugging
        env_file:
            - ./enredarte/.env
        depends_on:
            - db
    db:
        image: postgres:12.4-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        env_file: 
            - ./enredarte/.env

# Makes data persistent
volumes: 
    postgres_data: