# Generated by Django 2.2.10 on 2020-08-14 00:34

from django.db import migrations, models
import django.db.models.deletion
import proveedores.helpers


class Migration(migrations.Migration):

    # replaces = [
    #     ("core", "0001_initial"),
    #     ("core", "0002_auto_20190704_1709"),
    #     ("core", "0003_auto_20190705_1600"),
    #     ("core", "0004_auto_20190705_1913"),
    #     ("core", "0005_auto_20190705_1940"),
    #     ("core", "0006_auto_20190718_1239"),
    # ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstadoPedido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=128, unique=True)),
                ("detalles", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("medida", models.CharField(max_length=64)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio en $", max_digits=6
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsumosProducto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Insumo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
            ],
            options={"verbose_name_plural": "Localidades",},
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_provincia", models.CharField(default="AR-", max_length=10)),
                ("provincia", models.CharField(default="Provincia", max_length=50)),
            ],
            options={"ordering": ["provincia"],},
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128, unique=True)),
                ("descripcion", models.TextField(max_length=100)),
            ],
            options={"verbose_name_plural": "Unidades",},
        ),
        migrations.CreateModel(
            name="StockInsumo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Cantidad en Stock"
                    ),
                ),
                ("detalles", models.TextField(blank=True)),
                (
                    "insumo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Insumo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuit",
                    models.CharField(
                        help_text="Ingrese el CUIT con el siguiente formato: 20-12345678-9",
                        max_length=13,
                        unique=True,
                        validators=[proveedores.helpers.validar_cuit],
                    ),
                ),
                ("razon_social", models.CharField(max_length=64)),
                ("telefono", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("calle", models.CharField(max_length=64)),
                ("numero", models.CharField(max_length=4)),
                ("detalles", models.TextField(blank=True)),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="core.Localidad",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Proveedores",},
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(max_length=100)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio en $", max_digits=6
                    ),
                ),
                (
                    "insumos",
                    models.ManyToManyField(
                        through="core.InsumosProducto", to="core.Insumo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="localidad",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provincias",
                to="core.Provincia",
            ),
        ),
        migrations.AddField(
            model_name="insumosproducto",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.Producto"
            ),
        ),
        migrations.AddField(
            model_name="insumo",
            name="proveedores",
            field=models.ManyToManyField(to="core.Proveedor"),
        ),
        migrations.AddField(
            model_name="insumo",
            name="unidad_medida",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unidades",
                to="core.Unidad",
            ),
        ),
        migrations.RenameField(
            model_name="localidad", old_name="nombre", new_name="localidad",
        ),
        migrations.AddField(
            model_name="localidad",
            name="cod_postal",
            field=models.CharField(
                default=5921, max_length=10, verbose_name="Codigo Postal"
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="localidad",
            options={"ordering": ["localidad"], "verbose_name_plural": "Localidades"},
        ),
        migrations.AlterField(
            model_name="localidad",
            name="cod_postal",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField(auto_now_add=True)),
                (
                    "precio_final",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio en $", max_digits=6
                    ),
                ),
                ("detalles", models.TextField(blank=True)),
                (
                    "estado_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="core.EstadoPedido",
                    ),
                ),
                ("productos_pedido", models.ManyToManyField(to="core.Producto")),
            ],
        ),
    ]
