# Generated by Django 2.2.3 on 2019-11-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_delete_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localidad",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provincias",
                to="core.Provincia",
            ),
        ),
    ]
