# Generated by Django 2.2.10 on 2020-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20191101_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localidad",
            name="cod_postal",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
