# Generated by Django 2.2.3 on 2019-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_productos_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, help_text='Última vez actualizado'),
        ),
    ]
