# Generated by Django 2.2.10 on 2020-05-29 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20191101_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='Fecha de entrega estimada'),
            preserve_default=False,
        ),
    ]
