# Generated by Django 2.2.10 on 2020-06-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_fecha_entrega_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Creado'), (2, 'En proceso'), (3, 'Entregado'), (4, 'Pagado')], default=1),
        ),
    ]
