# Generated by Django 2.2.10 on 2020-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_estado_pedidos_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "Creado"),
                    (1, "En proceso"),
                    (2, "Entregado"),
                    (3, "Pagado"),
                ],
                default=0,
            ),
        ),
    ]
