# Generated by Django 2.2.10 on 2020-08-16 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("pedidos", "0011_agg_base_model")]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="fecha_pedido",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Fecha de pedido"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha_entrega",
            field=models.DateField(blank=True, verbose_name="Fecha de entrega estimada"),
        ),
        migrations.AlterField(
            model_name="productospedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_pedidos",
                to="pedidos.Pedido",
            ),
        ),
    ]
