# Generated by Django 2.2.10 on 2020-09-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0014_auto_20200827_1250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="precio_total",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Precio en $", max_digits=6
            ),
        ),
    ]
