# Generated by Django 2.2.10 on 2020-09-07 03:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0015_auto_20200906_2205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="precio_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Precio en $",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
