# Generated by Django 2.2.10 on 2020-10-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0016_auto_20200907_0005"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productospedido", options={"verbose_name_plural": "Productos Pedidos"},
        ),
    ]
