# Generated by Django 2.2.13 on 2020-11-02 21:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0017_auto_20201009_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="descuento",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="% de descuento",
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
