# Generated by Django 2.2.13 on 2020-11-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0021_ordentrabajo"),
    ]

    operations = [
        migrations.RemoveField(model_name="ordentrabajo", name="cliente",),
        migrations.AlterField(
            model_name="ordentrabajo",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "Creado"),
                    (1, "Marcado"),
                    (2, "Cortado"),
                    (3, "Ensamblado"),
                    (4, "Lijado"),
                    (5, "Acabado"),
                    (6, "Traslado"),
                    (7, "Finalizada"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="ordentrabajo",
            name="pedido",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orden_de_trabajo",
                to="pedidos.Pedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "Creado"),
                    (1, "Pagado"),
                    (2, "En proceso"),
                    (3, "Listo para entrega"),
                    (4, "Finalizado"),
                ],
                default=0,
            ),
        ),
    ]
