# Generated by Django 2.2.13 on 2020-11-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0022_auto_20201116_2005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordentrabajo",
            name="pedido",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orden_de_trabajo",
                to="pedidos.Pedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "Creado"),
                    (1, "Pagado"),
                    (2, "En proceso"),
                    (3, "Listo para entrega"),
                    (4, "Finalizado"),
                    (9, "Cancelado"),
                ],
                default=0,
            ),
        ),
    ]
