# Generated by Django 2.2.13 on 2020-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0023_auto_20201118_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordentrabajo",
            name="estado",
            field=models.IntegerField(
                choices=[(0, "Iniciada"), (1, "Finalizada")], default=0
            ),
        ),
    ]
