# Generated by Django 2.2.13 on 2020-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0024_auto_20201119_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="pagado",
            field=models.BooleanField(default=False, verbose_name="Pagado"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "Creado"),
                    (1, "En proceso"),
                    (2, "Listo para entrega"),
                    (3, "Entregado"),
                    (9, "Cancelado"),
                ],
                default=0,
            ),
        ),
    ]
