# Generated by Django 2.2.13 on 2020-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0025_auto_20201126_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.IntegerField(
                choices=[
                    (0, "Creado"),
                    (1, "En proceso"),
                    (2, "Listo para entrega"),
                    (3, "Entregado"),
                    (4, "Cancelado"),
                ],
                default=0,
            ),
        ),
    ]
