# Generated by Django 2.2.13 on 2020-12-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0027_pedido_fecha_entrega_real"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos",
                to="clientes.Cliente",
            ),
        ),
    ]
