# Generated by Django 2.2.3 on 2019-07-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_auto_20190722_1510"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("medida", models.CharField(max_length=64)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio en $", max_digits=6
                    ),
                ),
                ("proveedores", models.ManyToManyField(to="core.Proveedor")),
            ],
        ),
        migrations.CreateModel(
            name="InsumosProducto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="productos.Insumo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128, unique=True)),
                ("descripcion", models.TextField(max_length=100)),
            ],
            options={"verbose_name_plural": "Unidades",},
        ),
        migrations.CreateModel(
            name="StockInsumo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Cantidad en Stock"
                    ),
                ),
                ("detalles", models.TextField(blank=True)),
                (
                    "insumo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="productos.Insumo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estructura",
                    models.CharField(
                        choices=[
                            ("unico", "Producto único"),
                            ("padre", "Producto padre"),
                            ("hijo", "Producto hijo"),
                        ],
                        default="unico",
                        max_length=10,
                    ),
                ),
                (
                    "cod_producto",
                    models.CharField(
                        help_text="Código único de producto para identificación",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio en $", max_digits=6
                    ),
                ),
                (
                    "insumos",
                    models.ManyToManyField(
                        through="productos.InsumosProducto", to="productos.Insumo"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sólo elija un producto padre si está creando un producto hijo.                    Deje en blanco si este es un producto único.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="productos.Producto",
                        verbose_name="Producto padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "AbstractProduct",
                "verbose_name_plural": "AbstractProducts",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="insumosproducto",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="productos.Producto"
            ),
        ),
        migrations.AddField(
            model_name="insumo",
            name="unidad_medida",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unidades",
                to="productos.Unidad",
            ),
        ),
    ]
