# Generated by Django 2.2.3 on 2019-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
