# Generated by Django 2.2.3 on 2019-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('productos', '0002_auto_20190723_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='proveedores',
            field=models.ManyToManyField(to='proveedores.Proveedor'),
        ),
    ]
