# Generated by Django 2.2.3 on 2019-07-25 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_insumo_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cod_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estructura',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='parent',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(help_text='Precio en $'),
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('precio_venta', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
    ]
