# Generated by Django 2.2.3 on 2019-07-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to='productos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
    ]
