# Generated by Django 2.2.3 on 2019-07-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20190731_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
