# Generated by Django 2.2.3 on 2019-07-31 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20190731_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
