# Generated by Django 2.2.3 on 2019-08-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Largo, Alto', max_length=64)),
                ('detalles', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Caracteristica',
                'verbose_name_plural': 'Caracteristicas',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicasProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(help_text='Valor de la medida para el producto')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Caracteristica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.ManyToManyField(through='productos.CaracteristicasProducto', to='productos.Caracteristica'),
        ),
    ]
