# Generated by Django 2.2.3 on 2019-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20190809_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasproducto',
            name='valor',
            field=models.PositiveIntegerField(help_text='Valor de la medida en cm para el producto'),
        ),
    ]
