# Generated by Django 2.2.3 on 2019-11-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20191101_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristicasproducto',
            name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='caracteristicasproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio de compra al proveedor en $', max_digits=6),
        ),
        migrations.DeleteModel(
            name='Caracteristica',
        ),
        migrations.DeleteModel(
            name='CaracteristicasProducto',
        ),
    ]
