# Generated by Django 2.2.3 on 2019-11-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20191126_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Alto en cm', max_digits=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Ancho en cm', max_digits=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='insumoBase',
            field=models.ForeignKey(default=1, help_text='Insumo utilizado para la base', on_delete=django.db.models.deletion.PROTECT, related_name='BaseInsumo', to='productos.Insumo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='insumoLados',
            field=models.ForeignKey(default=2, help_text='Insumo utilizado para los lados', on_delete=django.db.models.deletion.PROTECT, related_name='LadoInsumo', to='productos.Insumo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Largo en cm', max_digits=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo',
            field=models.PositiveIntegerField(default=30, help_text='Minutos para realizar el producto'),
        ),
    ]
