# Generated by Django 2.2.3 on 2019-11-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20191126_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='insumoBase',
            new_name='insumo_base',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='insumoLados',
            new_name='insumo_lados',
        ),
    ]
