# Generated by Django 2.2.10 on 2020-09-07 03:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0019_add_base_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumo",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio de compra al proveedor en $",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="alto",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Alto en cm",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="ancho",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Ancho en cm",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="largo",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Largo en cm",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="stockinsumo",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Cantidad en Stock",
            ),
        ),
    ]
