# Generated by Django 2.2.10 on 2020-09-27 10:31

from django.db import migrations, models
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0020_auto_20200907_0005"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="imagen_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="imagen_ppoi",
            field=imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
        ),
        migrations.AddField(
            model_name="productimage",
            name="imagen_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="imagen",
            field=imagefield.fields.ImageField(
                blank=True,
                height_field="imagen_height",
                upload_to="productos/",
                width_field="imagen_width",
            ),
        ),
    ]
