# Generated by Django 2.2.10 on 2020-09-28 06:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0020_auto_20200907_0005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumo",
            name="medida",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Medida del insumo",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="insumo",
            name="proveedores",
            field=models.ManyToManyField(
                help_text="Proveedores que venden este insumo",
                related_name="insumos",
                to="proveedores.Proveedor",
            ),
        ),
    ]
