# Generated by Django 2.2.10 on 2020-09-28 21:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0021_auto_20200928_0308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumosproducto",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
