# Generated by Django 2.2.10 on 2020-10-20 01:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0023_auto_20201009_1544"),
    ]

    operations = [
        migrations.CreateModel(
            name="Irregular",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="productos.Producto",
                    ),
                ),
                (
                    "detalles",
                    models.TextField(
                        blank=True, help_text="Detalles de armado del producto"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de venta del producto en $",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Irregular",
                "verbose_name_plural": "Productos Irregulares",
            },
            bases=("productos.producto",),
        ),
        migrations.RemoveField(model_name="producto", name="alto",),
        migrations.RemoveField(model_name="producto", name="ancho",),
        migrations.RemoveField(model_name="producto", name="insumo_base",),
        migrations.RemoveField(model_name="producto", name="insumo_lados",),
        migrations.RemoveField(model_name="producto", name="largo",),
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[("regular", "regular"), ("irregular", "irregular")],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Regular",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="productos.Producto",
                    ),
                ),
                (
                    "largo",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Largo en cm",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "ancho",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Ancho en cm",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "alto",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Alto en cm",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "insumo_base",
                    models.ForeignKey(
                        default=1,
                        help_text="Insumo utilizado para la base",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="BaseInsumo",
                        to="productos.Insumo",
                    ),
                ),
                (
                    "insumo_lados",
                    models.ForeignKey(
                        default=2,
                        help_text="Insumo utilizado para los lados",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="LadoInsumo",
                        to="productos.Insumo",
                    ),
                ),
            ],
            options={"verbose_name": "Regular", "verbose_name_plural": "Regulars",},
            bases=("productos.producto",),
        ),
    ]
