# Generated by Django 2.2.10 on 2020-10-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0024_auto_20201019_2209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[("regular", "Regular"), ("irregular", "Irregular")],
                default="regular",
                max_length=20,
            ),
        ),
    ]
