# Generated by Django 2.2.13 on 2020-10-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0026_auto_20201026_1437"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="irregular",
            options={
                "permissions": [
                    ("change_product_price", "Can modify an Irregular product price")
                ],
                "verbose_name": "Producto Irregular",
                "verbose_name_plural": "Productos Irregulares",
            },
        ),
    ]
