# Generated by Django 2.2.13 on 2020-11-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0027_auto_20201027_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumosproducto",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insumos_por_producto",
                to="productos.Producto",
            ),
        ),
    ]
