# Generated by Django 2.2.3 on 2019-11-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_hora', models.PositiveSmallIntegerField(blank=True, help_text='Precio de la hora de trabajo')),
                ('precio_pintado', models.PositiveSmallIntegerField(blank=True, help_text='Precio de la pintura/apliques incluídos en el producto')),
                ('ganancia_por_mayor', models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de ganancia por mayor')),
                ('ganancia_por_menor', models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de ganancia por menor')),
                ('ganancia_fibrofacil', models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de ganancia aplicada al fibrofacil')),
            ],
        ),
    ]
