# Generated by Django 2.2.3 on 2019-11-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variables',
            new_name='Variable',
        ),
    ]
