# Generated by Django 2.2.3 on 2019-07-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0006_auto_20190718_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=64)),
                ('calle', models.CharField(max_length=64)),
                ('numero', models.CharField(max_length=6)),
                ('detalles', models.TextField(blank=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='gestion.Localidad')),
            ],
            options={
                'db_table': 'clientes_cliente',
                'ordering': ['nombre', 'apellido'],
            },
        ),
    ]
