# Generated by Django 2.2.10 on 2020-08-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_auto_20200814_1145"),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="fecha_creacion",),
        migrations.AlterField(
            model_name="cliente",
            name="localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.Localidad"
            ),
        ),
    ]
