# Generated by Django 2.2.10 on 2020-08-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_deleted_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clientes",
                to="core.Localidad",
            ),
        ),
    ]
