# Generated by Django 2.2.10 on 2020-08-16 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("compras", "0003_auto_20191101_1227")]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="fecha_compra",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="proveedores.Proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="insumoscompra",
            name="compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insumos_comprados",
                to="compras.Compra",
            ),
        ),
    ]
