# Generated by Django 2.2.10 on 2020-09-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0005_agg_base_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumoscompra",
            name="precio_compra",
            field=models.DecimalField(
                decimal_places=2, help_text="Precio unitario", max_digits=6
            ),
        ),
    ]
