# Generated by Django 2.2.10 on 2020-10-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0008_auto_20200928_1914"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insumoscompra", options={"verbose_name_plural": "Insumos Comprados"},
        ),
    ]
