# Generated by Django 2.2.13 on 2020-11-25 13:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0009_auto_20201009_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumoscompra",
            name="precio_compra",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio total",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
