# Generated by Django 2.2.10 on 2020-09-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0004_campos_no_requeridos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
